# Generated by Django 3.1.6 on 2021-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210217_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начат'),
        ),
    ]
