# Generated by Django 3.1.6 on 2021-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='polls', to='polls.Question'),
        ),
    ]
