# Generated by Django 3.1.6 on 2021-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210328_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(blank=True, to='polls.Question'),
        ),
    ]
