# Generated by Django 3.1.6 on 2021-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210328_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
